# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'checkupdate.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CheckUpdate(object):
    def setupUi(self, CheckUpdate):
        CheckUpdate.setObjectName("CheckUpdate")
        CheckUpdate.resize(400, 300)
        CheckUpdate.setMinimumSize(QtCore.QSize(400, 300))
        CheckUpdate.setMaximumSize(QtCore.QSize(400, 300))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        CheckUpdate.setFont(font)
        self.verticalLayoutWidget = QtWidgets.QWidget(CheckUpdate)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(8, 8, 381, 281))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.progressBar = QtWidgets.QProgressBar(self.verticalLayoutWidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)

        self.retranslateUi(CheckUpdate)
        QtCore.QMetaObject.connectSlotsByName(CheckUpdate)

    def retranslateUi(self, CheckUpdate):
        _translate = QtCore.QCoreApplication.translate
        CheckUpdate.setWindowTitle(_translate("CheckUpdate", "Проверка обновления"))
        self.label.setText(_translate("CheckUpdate", "Текущая версия: 1.0.0"))
        self.label_2.setText(_translate("CheckUpdate", "Доступное обновление: 1.0.1"))
        self.pushButton.setText(_translate("CheckUpdate", "Проверить наличене обновлений"))
        self.pushButton_2.setText(_translate("CheckUpdate", "Скачать"))
        self.pushButton_3.setText(_translate("CheckUpdate", "Закрыть"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CheckUpdate = QtWidgets.QDialog()
    ui = Ui_CheckUpdate()
    ui.setupUi(CheckUpdate)
    CheckUpdate.show()
    sys.exit(app.exec_())
